
import { world, system, ItemStack, DynamicPropertiesDefinition, MinecraftDimensionTypes } from "@minecraft/server";
import { ActionFormData, ModalFormData } from "@minecraft/server-ui";
import { WORLDS, STORY } from "./story_data.js";
const NS="nexus:"; const MAX_LEVEL=100;
world.afterEvents.worldInitialize.subscribe(({propertyRegistry})=>{const d=new DynamicPropertiesDefinition();["level","xp","stage","unlocked","quest","ending_truth","ending_mercy","ending_power"].forEach(k=>d.defineString(NS+k,4096));propertyRegistry.registerEntityTypeDynamicProperties(d,"minecraft:player");});
function get(p,k,def="0"){return p.getDynamicProperty(NS+k)??def} function set(p,k,v){p.setDynamicProperty(NS+k,String(v))}
function unlocked(p){return new Set((get(p,"unlocked","nexus")).split(',').filter(Boolean))} function unlock(p,id){let s=unlocked(p);s.add(id);set(p,"unlocked",[...s].join(','));}
function init(p){if(!p.hasTag('nexus_init')){set(p,'level','1');set(p,'xp','0');set(p,'stage','1');set(p,'quest','1');set(p,'unlocked','nexus,emberglass');p.addTag('nexus_init');p.sendMessage('§bEchoes of the Nexus: your private progression has begun. Use /scriptevent nexus:menu open.');}}
world.afterEvents.playerSpawn.subscribe(e=>init(e.player)); system.runInterval(()=>{for(const p of world.getPlayers()){init(p);p.onScreenDisplay.setActionBar(`§dNexus Lv ${get(p,'level')} §7XP ${get(p,'xp')} §6Stage ${get(p,'stage')}`)}},80);
function addXp(p,n){let xp=+get(p,'xp'), lvl=+get(p,'level'), stage=+get(p,'stage');xp+=n;while(lvl<MAX_LEVEL && xp>=lvl*100){xp-=lvl*100;lvl++;p.sendMessage(`§aNexus level ${lvl} reached.`); if(lvl>50 && stage<2 && (Math.random()<0.03||lvl>=100)){stage=2;p.sendMessage('§6Second Stage awakened: Echo Surge unlocked.');}}
 if(lvl>=100&&stage<2)stage=2; set(p,'xp',xp);set(p,'level',lvl);set(p,'stage',stage)}
function completeQuest(p){let q=+get(p,'quest','1');let node=STORY[q-1]; if(!node)return endings(p); addXp(p,node.rewardXp); if(node.unlock)unlock(p,node.unlock); set(p,'ending_'+node.choice,+get(p,'ending_'+node.choice,'0')+1); set(p,'quest',q+1); p.sendMessage(`§eCompleted: ${node.title}`); if(q%10===0){p.dimension.spawnEntity(`nexus:${node.world}_boss`,p.location); world.sendMessage(`§c${p.name} has awakened ${WORLDS.find(w=>w.id===node.world).boss}!`);} }
function teleport(p,id){if(!unlocked(p).has(id)){p.sendMessage('§cThis world is still sealed by story conditions.');return} let i=WORLDS.findIndex(w=>w.id===id); let x=10000+i*600,z=10000+i*600;p.teleport({x,y:90,z},{dimension:world.getDimension(MinecraftDimensionTypes.overworld)});p.runCommandAsync(`music play music.${id} 1 1 loop`);p.sendMessage(`§bTeleported to ${WORLDS[i].name}. Invite friends to visit these coordinates and help.`)}
function menu(p){const f=new ActionFormData().title('Echoes of the Nexus').body(`Level ${get(p,'level')} / Quest ${get(p,'quest')}`);f.button('Complete current quest');f.button('Teleport');f.button('Character sheet');f.show(p).then(r=>{if(r.canceled)return;if(r.selection===0)completeQuest(p);if(r.selection===1)tpMenu(p);if(r.selection===2)p.sendMessage(`§dStats: stage ${get(p,'stage')}, unlocked ${get(p,'unlocked')}`);});}
function tpMenu(p){const f=new ActionFormData().title('Unlocked Worlds');let arr=WORLDS.filter(w=>unlocked(p).has(w.id));arr.forEach(w=>f.button(w.name));f.show(p).then(r=>{if(!r.canceled)teleport(p,arr[r.selection].id)});}
function endings(p){let t=+get(p,'ending_truth'),m=+get(p,'ending_mercy'),pw=+get(p,'ending_power');let e=t>=m&&t>=pw?'Truth Ending: the Nexus becomes an open archive.':m>=pw?'Mercy Ending: divided worlds heal slowly.':'Power Ending: you crown yourself Warden of Echoes.';p.sendMessage('§6'+e)}
world.afterEvents.scriptEventReceive.subscribe(e=>{if(e.id==='nexus:menu'&&e.sourceEntity?.typeId==='minecraft:player')menu(e.sourceEntity); if(e.id==='nexus:xp'&&e.sourceEntity?.typeId==='minecraft:player')addXp(e.sourceEntity,Number(e.message)||50);});
world.afterEvents.entityDie.subscribe(e=>{let p=e.damageSource.damagingEntity; if(p?.typeId==='minecraft:player' && e.deadEntity.typeId.startsWith('nexus:')) addXp(p,150);});
